### PR TITLE
Fix import

### PR DESCRIPTION
**Pull request by killpanda**
* fix some incorrect imports.
* fix OX X notification feature.
* install pyobjc if platform is OS X.

### CODE REVIEW

**Comment by killpanda** [comment]
Could you review this PR?

**Comment by taizilongxu** [comment]
hi, sorring about that, waiting a moment, I will check it tonight : )

**Comment by killpanda** [comment]
Thanks very much.

**Comment by taizilongxu** [comment]
OK 我更了10.10.5后正常了 可能是我这里的问题 : )

**Comment by killpanda** [comment]
:+1:

**Pull request merged**
